apis/urls.py
from django.urls import path, include, re_path
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required

from rest_framework import permissions

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from apps import accounts

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    # apps
    path('', include('apps.accounts.urls', namespace='accounts')),
    path('home/', include('apps.home.urls', namespace='home')),
    path('incident/', include('apps.incident.urls', namespace='incident')),
    path('location/', include('apps.location.urls', namespace='location')),
    path('terminal/', include('apps.terminal.urls', namespace='terminal')),


    # tinymce
    path('tinymce/', login_required(include('tinymce.urls')), name='tinymce'),

    # swagger api documentation
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

apps/accounts/urls.py
from django.urls import path
from apps.accounts.views import (
    LoginView, LogoutView, CustomPasswordChangeView, ProfileView, PermissionDeniedView
)

app_name = "accounts"


urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('password-changed/', CustomPasswordChangeView.as_view(), name='password_changed'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('permission-denied/', PermissionDeniedView.as_view(), name='permission_denied'),
]

apps/home/urls.py
from django.urls import path
from apps.home.views import (
    HomeView
)

app_name = "home"


urlpatterns = [
    path('index/', HomeView.as_view(), name='home'),
]

apps/incident/urls.py
from django.urls import path
from apps.incident.views import (
    IncidentListView, IncidentDetailView, IncidentMapView,
    get_incident_types_by_country, get_involved_actors_by_country
)

app_name = "incident"


urlpatterns = [
    path('ajax/incident-types/', get_incident_types_by_country, name='get_incident_types_by_country'),
    path('ajax/involved-actors/', get_involved_actors_by_country, name='get_involved_actors_by_country'),
    path('list/', IncidentListView.as_view(), name='incident_list'),
    path('detail/<int:pk>/', IncidentDetailView.as_view(), name='incident_detail'),
    path('list-maps/', IncidentMapView.as_view(), name='incident_list_maps'),
]

apps/terminal/urls.py
from django.urls import path
from apps.terminal.views import (
    TerminalView, IncidentCreateView, IncidentUpdateView, IncidentDeleteView
)

app_name = "terminal"


urlpatterns = [
    path('dashboard/', TerminalView.as_view(), name='terminal_dashboard'),
    path('incident-create/', IncidentCreateView.as_view(), name='incident_create'),
    path("incident/<int:pk>/edit/", IncidentUpdateView.as_view(), name="incident_update"),
    path("incident/<int:pk>/delete/", IncidentDeleteView.as_view(), name="incident_delete"),
]

core/urls.py
import os
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apis.urls')),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from django.contrib.auth import get_user_model

User = get_user_model()


class BaseModel(models.Model):
    class StatusChoices(models.TextChoices):
        PUBLISHED = 'PUBLISHED', _('PUBLISHED')
        UNPUBLISHED = 'UNPUBLISHED', _('UNPUBLISHED')
        ARCHIVED = 'ARCHIVED', _('ARCHIVED')

    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        editable=False
    )
    posted_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="issue_posted_user",
        verbose_name=_("রিপোর্টারের নাম")
    )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="issue_updated_user",
        verbose_name=_("পরিপোর্ট হালনাগাদ কারীর নাম")
    )

    class Meta:
        abstract = True
        app_label = 'base'

base/views.py
from django.shortcuts import render

# Create your views here.

core/templates/base/css.html
{% load static %}

<!-- jvectormap -->
<link href="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.2.css' %}" rel="stylesheet">
<link href="{% static 'assets/plugins/fullcalendar/vanillaCalendar.css' %}" rel="stylesheet" type="text/css"/>

<link href="{% static 'assets/plugins/morris/morris.css' %}" rel="stylesheet">

<link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/css/icons.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/css/incidents.css' %}" rel="stylesheet" type="text/css">

<!-- Magnific popup -->
<link href="{% static 'assets/plugins/magnific-popup/magnific-popup.css' %}" rel="stylesheet" type="text/css">

<!-- flatpickr -->
<link rel="stylesheet" href="{% static 'assets/css/flatpickr.min.css' %}">

<!-- select2 -->
<link href="{% static 'assets/css/select2.min.css' %}" rel="stylesheet"/>

<!-- dropzone files -->
<link href="{% static 'assets/css/dz_file.css' %}" rel="stylesheet"/>

<!-- upper css -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>

core/templates/base/footer.html
{% load static %}

<footer class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        © 2025
                    </div>
                </div>
            </div>
        </footer>

core/templates/base/header.html
{% load static %}

<header id="topnav">
    <div class="topbar-main">
        <div class="container-fluid">

            <!-- Logo container-->
            <div class="logo">
                <!-- Text Logo -->
                <!--<a href="index.html" class="logo">-->
                <!--Zoter-->
                <!--</a>-->
                <!-- Image Logo -->
                <a href="{% if request.user.is_administrator %}{% url 'home:home' %}{% else %}{% url 'terminal:terminal_dashboard' %}{% endif %}" class="logo">
                    <img src="{% static 'assets/images/logo.png' %}" alt="" class="logo-large">
                </a>
            </div>
            <!-- End Logo container-->


            <div class="menu-extras topbar-custom">

                <ul class="list-inline float-right mb-0">
                    <!-- User-->
                    <li class="list-inline-item dropdown notification-list">
                        <a class="nav-link dropdown-toggle arrow-none waves-effect nav-user" data-toggle="dropdown"
                           href="#" role="button"
                           aria-haspopup="false" aria-expanded="false">
                            <img src="{% static 'assets/images/users/avatar-1.jpg' %}" alt="user"
                                 class="rounded-circle">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                            <!-- item-->
                            <div class="dropdown-item noti-title">
                                <h5>Welcome</h5>
                            </div>
                            <a class="dropdown-item" href="#"><i class="mdi mdi-account-circle m-r-5 text-muted"></i>
                                Profile</a>
                            <a class="dropdown-item" href="{% url 'accounts:password_changed' %}"><i class="mdi mdi-settings m-r-5 text-muted"></i>Password Change</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i
                                    class="mdi mdi-logout m-r-5 text-muted"></i> Logout</a>
                        </div>
                    </li>
                    <li class="menu-item list-inline-item">
                        <!-- Mobile menu toggle-->
                        <a class="navbar-toggle nav-link">
                            <div class="lines">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                        </a>
                        <!-- End mobile menu toggle-->
                    </li>

                </ul>

            </div>
            <!-- end menu-extras -->

            <div class="clearfix"></div>

        </div> <!-- end container -->
    </div>
    <!-- end topbar-main -->

    <!-- MENU Start -->
    <div class="navbar-custom">
        <div class="container-fluid">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu text-center">
                    {% if request.user.is_administrator %}
                        <li class="has-submenu ">
                            <a href="{% url 'home:home' %}"><i class="mdi mdi-airplay"></i>Home</a>
                        </li>
                        <li class="has-submenu ">
                            <a href="{% url 'incident:incident_list' %}"><i class="mdi mdi-bullseye"></i>Incidents</a>
                        </li>
                    {% elif request.user.is_operator %}
                        <li class="has-submenu ">
                            <a href="{% url 'terminal:terminal_dashboard' %}"><i class="mdi mdi-airplay"></i>Dashboard</a>
                        </li>
                    {% endif %}
                </ul>


                <!-- End navigation menu -->
            </div> <!-- end #navigation -->
        </div> <!-- end container -->
    </div> <!-- end navbar-custom -->
</header>

core/templates/base/js.html
{% load static %}

<!-- jQuery  -->
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/modernizr.min.js' %}"></script>
<script src="{% static 'assets/js/waves.js' %}"></script>
<script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'assets/js/jquery.nicescroll.js' %}"></script>
<script src="{% static 'assets/js/jquery.scrollTo.min.js' %}"></script>

<script src="{% static 'assets/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js' %}"></script>
<script src="{% static 'assets/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>

<script src="{% static 'assets/plugins/skycons/skycons.min.js' %}"></script>
<script src="{% static 'assets/plugins/fullcalendar/vanillaCalendar.js' %}"></script>
<script src="{% static 'assets/plugins/raphael/raphael-min.js' %}"></script>
<script src="{% static 'assets/plugins/morris/morris.min.js' %}"></script>

<script src="{% static 'assets/pages/dashborad.js' %}"></script>

<!-- Gmaps file -->
{#<script src="{% static 'assets/plugins/gmaps/gmaps.min.js' %}"></script>#}
<!-- demo codes -->
{#<script src="{% static 'assets/pages/gmaps.js' %}"></script>#}

<!-- App js -->
<script src="{% static 'assets/js/app.js' %}"></script>

<!-- Magnific popup -->
<script src="{% static 'assets/plugins/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'assets/pages/lightbox.js' %}"></script>

<!-- flatpickr -->
<script src="{% static 'assets/js/flatpickr.min.js' %}"></script>

<!--Wysiwig js-->
<script src="{% static 'assets/plugins/tinymce/tinymce.min.js' %}"></script>
<script src="{% static 'assets/pages/editor.init.js' %}"></script>

<!-- select2 -->
<script src="{% static 'assets/js/select2.min.js' %}"></script>

<!-- dropzone files -->
<script src="{% static 'assets/js/dz_file.js' %}"></script>

<!-- google maps api -->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCtSAR45TFgZjOs4nBFFZnII-6mMHLfSYI"></script>

core/templates/base/sidebar.html
{% load static %}